-- insercion Juego

USE PROYECTO_PEDIDOS;

INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Anne Frank Remembered', 'Samsung', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Set Me Free (Emporte-moi)', 'Sharp', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Welcome to L.A.', 'Nokia', 'Drama|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Ingmar Bergman Makes a Movie (Ingmar Bergman gör en film)', 'Coolpad', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mr. Troop Mom', 'Micromax', 'Children|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Radio Free Albemuth', 'ZTE', 'Drama|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('War Dance', 'ZTE', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Sharpe''s Gold', 'Allview', 'Action|Adventure|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Grace of My Heart', 'HTC', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Nine Months', 'Lenovo', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Jab We Met', 'Oppo', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('It''s in the Water', 'Archos', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('In the Hands of the Gods', 'Honor', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Tremors 3: Back to Perfection', 'Sony', 'Comedy|Horror|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Poison Ivy', 'Samsung', 'Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Moonfleet', 'Vertu', 'Adventure|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Miffo', 'BenQ-Siemens', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Dead of Winter', 'ZTE', 'Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Food Stamped', 'Amoi', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Questo piccolo grande amore', 'Samsung', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hard Times', 'Eten', 'Action|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Monster, The', 'Lenovo', 'Comedy|Horror|Mystery|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Woodcarver', 'Lava', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Simple-Minded Murder, The (Enfaldige mördaren, Den)', 'Orange', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Sleepwalk with Me', 'Samsung', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Facts of Murder', 'Asus', 'Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('End of St. Petersburg, The (Konets Sankt-Peterburga)', 'Motorola', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Good Evening, Mr. Wallenberg (God afton, Herr Wallenberg)', 'QMobile', 'Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Amazon Women on the Moon', 'Vodafone', 'Comedy|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Calamity Jane', 'HTC', 'Musical|Western');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Pronto', 'Philips', 'Comedy|Crime|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Taking Care of Business', 'LG', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Christmas in August (Palwolui Christmas)', 'Lava', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Boy, Did I Get a Wrong Number!', 'Sewon', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Natural, The', 'HTC', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Madame Sousatzka', 'Acer', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hell (L''enfer)', 'Coolpad', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('What? (Che?)', 'Micromax', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Juno and the Paycock', 'BLU', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Oh, God! You Devil', 'Motorola', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Troll Hunter, The (Trolljegeren)', 'vivo', 'Fantasy|Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Scarlet and the Black, The', 'LG', 'Action|Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Handsome Harry', 'Sagem', 'Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Adventurers', 'ZTE', 'Action|Adventure|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Bagdad Cafe (Out of Rosenheim)', 'Icemobile', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Intruder, The', 'Xiaomi', 'Drama|Mystery|Romance|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Wind Chill', 'alcatel', 'Drama|Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Birds, the Bees and the Italians, The (Signore & signori)', 'Samsung', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Cry_Wolf (a.k.a. Cry Wolf)', 'Orange', 'Drama|Horror|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Big Bounce, The', 'O2', 'Comedy|Crime|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Buccaneer, The', 'Motorola', 'Adventure|Drama|Romance|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Summer Hours (Heure d''été, L'')', 'alcatel', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hidden Face, The (La cara oculta)', 'Kyocera', 'Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Race with the Devil', 'Xiaomi', 'Action|Horror|Mystery');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Leaving (Partir)', 'Micromax', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Young Törless, The (Junge Törless, Der)', 'Gigabyte', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('In Like Flint', 'Apple', 'Action|Adventure|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Nelly & Monsieur Arnaud', 'Asus', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mr. Blandings Builds His Dream House', 'Gigabyte', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Flight of the Navigator', 'Samsung', 'Adventure|Children|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Standing Still', 'Celkon', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Crazy People', 'Kyocera', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('United', 'ZTE', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Lucky 7', 'Samsung', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Paul', 'alcatel', 'Adventure|Comedy|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Russell Peters: Outsourced', 'Sony', 'Comedy|Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Asterix & Obelix: God Save Britannia (Astérix et Obélix: Au service de Sa Majesté)', 'Infinix', 'Adventure|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Drowning Mona', 'Meizu', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Big White, The', 'BlackBerry', 'Comedy|Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Undercover Brother', 'Samsung', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Horseman, The', 'alcatel', 'Crime|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Now and Then', 'Kyocera', 'Children|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Russians Are Coming, the Russians Are Coming, The', 'Wiko', 'Comedy|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Without Love', 'HTC', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Breaking the Rules', 'Lava', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Transcendence', 'Sony', 'Drama|Sci-Fi|IMAX');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Duck Season (Temporada de patos)', 'Realme', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Occurrence at Owl Creek Bridge, An (La rivière du hibou)', 'Nokia', 'Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hansel & Gretel', 'Huawei', 'Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('''Hellboy'': The Seeds of Creation', 'Asus', 'Action|Adventure|Comedy|Documentary|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Day That Lasted 21 Years', 'BLU', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Call of the Wild, The', 'Nokia', 'Action|Adventure|Drama|Romance|Western');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Confiance règne, La', 'Nokia', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('One Tough Cop', 'Wiko', 'Action|Crime');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Outfit, The', 'QMobile', 'Crime|Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Winter Passing', 'Micromax', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Afternoon of a Torturer, The (Dupa-amiaza unui tortionar)', 'BlackBerry', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Arsène Lupin', 'Samsung', 'Mystery|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Summer Magic', 'Maxwest', 'Children|Comedy|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Year One', 'QMobile', 'Adventure|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hombre', 'HTC', 'Western');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Two Hands', 'Honor', 'Comedy|Crime|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Who Killed the Electric Car?', 'Motorola', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Normal Adolescent Behavior', 'Samsung', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Billu', 'Sony', 'Comedy|Drama|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Silver Bullet (Stephen King''s Silver Bullet)', 'Samsung', 'Adventure|Drama|Horror|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Dance with the Devil (Perdita Durango)', 'Lava', 'Action|Crime|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Deathmaker, The (Totmacher, Der)', 'ZTE', 'Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('State Fair', 'ZTE', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Glitterbug', 'Huawei', '(no genres listed)');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Next Karate Kid, The', 'Samsung', 'Action|Children|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Signal, The', 'Siemens', 'Horror|Sci-Fi|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Most Beautiful, The (Ichiban utsukushiku)', 'Sony', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('WWII IN HD', 'Celkon', '(no genres listed)');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Man on High Heels', 'Spice', 'Action|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Good Burger', 'verykool', 'Children|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Buud Yam', 'Samsung', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Loft', 'BLU', 'Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Village, The', 'Sony', 'Drama|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Words and Pictures', 'Allview', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('High School Musical 3: Senior Year', 'Panasonic', 'Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Christmas Carol: The Movie', 'Lava', 'Animation|Children');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Silent Partner', 'Samsung', 'Action|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Iraq for Sale: The War Profiteers', 'QMobile', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Climate of Change', 'Ulefone', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Army', 'Plum', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Princesas', 'Siemens', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('King Lear', 'Maxon', 'Comedy|Drama|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Three and Out (Deal Is a Deal, A)', 'Panasonic', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Doomsday', 'HTC', 'Action|Drama|Sci-Fi|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Monterey Pop', 'LG', 'Documentary|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Üvegtigris', 'vivo', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Weird Science', 'Philips', 'Comedy|Fantasy|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Trick ''r Treat', 'Micromax', 'Comedy|Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Tingler, The', 'LG', 'Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hollywood Canteen', 'Samsung', 'Comedy|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hours, The', 'LG', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Forger, The', 'Telit', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Red Salute', 'Lava', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Murder by Numbers', 'Samsung', 'Crime|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Gigot', 'MWg', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Faster', 'HTC', 'Action|Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Dream a Little Dream', 'Apple', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Card Player, The (Il cartaio)', 'alcatel', 'Crime|Horror|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Day, The', 'Micromax', 'Drama|Sci-Fi|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Operation Homecoming: Writing the Wartime Experience', 'Honor', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mr. Accident', 'Philips', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hoosiers (a.k.a. Best Shot)', 'Huawei', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Basic Instinct', 'Allview', 'Crime|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Three Fugitives', 'Oppo', 'Action|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('She-Devil', 'Spice', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('No Highway in the Sky', 'Samsung', 'Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Holes in My Shoes', 'Allview', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Whisper of the Heart (Mimi wo sumaseba)', 'Haier', 'Animation|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Aladdin and the King of Thieves', 'Motorola', 'Animation|Children|Comedy|Fantasy|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Saturday Night and Sunday Morning', 'Tecno', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Summer''s Tale, A (Conte d''été)', 'XOLO', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Che: Part One', 'HTC', 'Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Fanny', 'Pantech', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Equilibrium', 'Lenovo', 'Action|Sci-Fi|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Vali', 'Sony', 'Action|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Food of the Gods II', 'Asus', 'Horror|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Great Day in Harlem, A', 'LG', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Moomins on the Riviera (Muumit Rivieralla)', 'Honor', 'Animation|Children|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Shanghai Triad (Yao a yao yao dao waipo qiao)', 'BLU', 'Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('House', 'Motorola', 'Drama|Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Eighth Day, The (Den Åttonde dagen)', 'Mitac', 'Children|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Pennies from Heaven', 'LG', 'Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Butcher Boys (Bone Boys)', 'Wiko', 'Action|Comedy|Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Stuart: A Life Backward', 'BLU', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Notorious Landlady, The', 'Nokia', 'Comedy|Mystery');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Shock', 'Allview', 'Film-Noir|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Note by Note: The Making of Steinway L1037', 'Celkon', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mater and the Ghostlight', 'Cat', 'Animation|Children|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Pardes', 'LG', 'Action|Comedy|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Gypsy 83', 'Lenovo', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Prom Night in Mississippi', 'alcatel', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Eat', 'Asus', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Judgment at Nuremberg', 'LG', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Last Play at Shea, The', 'Philips', 'Documentary|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Tormento', 'WND', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Shunning, The', 'Nokia', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Kanal', 'Asus', 'Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Dunwich Horror, The', 'Vodafone', 'Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Incendiary', 'BLU', 'Drama|Mystery|Romance|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Benji the Hunted', 'Allview', 'Adventure|Children');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Jumbo (Billy Rose''s Jumbo)', 'Bird', 'Comedy|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Saw', 'Motorola', 'Horror|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Other Woman, The', 'BenQ-Siemens', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Big Knife, The', 'LG', 'Film-Noir');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Lair of the White Worm, The', 'Pantech', 'Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Pussy Riot: A Punk Prayer', 'YU', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Every Day', 'Micromax', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Secret World of Arrietty, The (Kari-gurashi no Arietti)', 'Acer', 'Animation|Children|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Human Capital (Il capitale umano)', 'LG', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Blaze', 'Nokia', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('R', 'BLU', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Thieves (Voleurs, Les)', 'LG', 'Crime|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Bomb It', 'Celkon', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Bigger Than Life', 'Lava', 'Drama|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('She Does Not Drink, Smoke or Flirt But... She Talks', 'Xiaomi', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Barcelona', 'Oppo', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('In Passing', 'Celkon', 'Drama|Fantasy|Mystery');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('November Man, The', 'Panasonic', 'Action|Crime|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('State of the Union', 'Lava', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Blue Dahlia, The', 'Sagem', 'Crime|Drama|Film-Noir|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Footloose', 'verykool', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('11 Harrowhouse', 'alcatel', 'Comedy|Crime');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hell''s Kitchen', 'Samsung', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Lemming', 'Sagem', 'Drama|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Concepción Arenal, la visitadora de cárceles', 'alcatel', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('7 Khoon Maaf', 'Vodafone', 'Drama|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Bandits (Bandidos)', 'Yezz', 'Action|Adventure|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('I Remember (Eu Me Lembro)', 'vivo', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Phantom Lover, The (Ye ban ge sheng)', 'Asus', 'Drama|Mystery|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Dreams of  a Life', 'QMobile', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Naked Gun 33 1/3: The Final Insult', 'Spice', 'Action|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Al-risâlah', 'verykool', 'Adventure|Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('3-Iron (Bin-jip)', 'Telit', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Music and Lyrics', 'BQ', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Revengers Tragedy', 'Huawei', 'Comedy|Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Melancholia', 'Celkon', 'Drama|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Our Summer in Provence', 'Vodafone', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Loving You', 'Samsung', 'Drama|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mortal Kombat', 'Asus', 'Action|Adventure|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Carmen Jones', 'Samsung', 'Drama|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Misérables in Concert, Les', 'Samsung', 'Drama|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Family Thing, A', 'Samsung', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Dark, The', 'Huawei', 'Horror|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Wind Chill', 'i-mobile', 'Drama|Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Pruitt-Igoe Myth, The', 'Samsung', 'Documentary|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Portrait of a Lady, The', 'Nokia', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Union, The', 'Celkon', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Internship, The', 'Apple', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Babylon 5: The Gathering', 'verykool', 'Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Cujo', 'LG', 'Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Moon Over Parador', 'Philips', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Sunburn', 'Allview', 'Action|Comedy|Crime');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Criminal Lovers', 'alcatel', 'Crime|Drama|Romance|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Godzilla''s Revenge (Gojira-Minira-Gabara: Oru Kaijû Daishingeki) (All Monsters Attack)', 'Spice', 'Children');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Tin Pan Alley', 'Apple', 'Drama|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Finding Vivian Maier', 'Lava', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('I Saw the Sun (Günesi gördüm)', 'HTC', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Zatoichi and the Chess Expert (Zatôichi Jigoku tabi) (Zatôichi 12)', 'Lenovo', 'Action|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Junior Bonner', 'Eten', 'Comedy|Drama|Western');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('So Long Letty', 'Samsung', 'Comedy|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hunters, The', 'Dell', 'Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Adventures of Robin Hood, The', 'LG', 'Action|Adventure|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hardcore', 'Pantech', 'Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mr. Saturday Night', 'Motorola', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Unprecedented: The 2000 Presidential Election', 'Siemens', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Kill for Me', 'Honor', 'Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Firm, The', 'Motorola', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Nomad (Köshpendiler)', 'Celkon', 'Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Set-Up, The', 'Sony', 'Drama|Film-Noir|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Vamp', 'Allview', 'Comedy|Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Half Life of Timofey Berezin, The (PU-239)', 'alcatel', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Empty Mirror, The', 'Oppo', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Devil''s Knot', 'Philips', 'Crime|Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Think Fast, Mr. Moto', 'Allview', 'Crime|Drama|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Christmas Carol, A (Scrooge)', 'Samsung', 'Drama|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('''R Xmas', 'Apple', 'Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Along the Ridge (Anche libero va bene)', 'T-Mobile', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Kandahar (Safar e Ghandehar)', 'Sendo', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Geography Club', 'Plum', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Garbage Warrior', 'Lenovo', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Last Run', 'Ericsson', 'Action|Crime|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Back to the Secret Garden', 'Siemens', 'Adventure|Children|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('In the Edges: The ''Grizzly Man'' Session ', 'verykool', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Birdman', 'Nokia', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('39 Steps, The', 'Panasonic', 'Drama|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Embracing', 'Celkon', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Earth Trembles, The (Terra trema: Episodio del mare, La)', 'Gigabyte', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('O Brother, Where Art Thou?', 'Allview', 'Adventure|Comedy|Crime');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Tomb of Ligeia, The', 'NEC', 'Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Short Film About John Bolton, A', 'HP', 'Fantasy|Horror|Mystery');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hundred-Foot Journey, The', 'XOLO', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Born in Flames', 'Energizer', 'Comedy|Drama|Fantasy|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Poison', 'Gigabyte', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Margaret', 'Huawei', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Looking Forward', 'BLU', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Lambada', 'LG', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Asylum Blackout', 'vivo', 'Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Decampitated', 'LG', 'Comedy|Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Thing, The', 'Sonim', 'Horror|Mystery|Sci-Fi|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Goodbye, South, Goodbye (Nan guo zai jian, nan guo)', 'NIU', 'Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Trick', 'QMobile', 'Action|Crime');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Puppet Master vs. Demonic Toys (Puppet Master 9)', 'Huawei', 'Comedy|Fantasy|Horror|Sci-Fi|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Pride and Prejudice', 'Sewon', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Topo, El', 'BLU', 'Fantasy|Western');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('White Reindeer, The (Valkoinen peura)', 'LG', 'Drama|Fantasy|Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('And the Pursuit of Happiness (La poursuite du bonheur)', 'Huawei', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Devil and the Holy Water', 'Wiko', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Burnt Money (Plata Quemada)', 'Lava', 'Action|Crime|Drama|Romance|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Harvie Krumpet', 'Xiaomi', 'Animation|Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Arabesque', 'Huawei', 'Adventure|Drama|Romance|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('God is Great, I''m Not (Dieu est grand, je suis toute petite)', 'Haier', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Jonathan Livingston Seagull', 'Asus', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Bullies', 'Tecno', 'Action|Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Life of Aleksis Kivi, The (Aleksis Kiven elämä)', 'Toshiba', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Harmony Game', 'Samsung', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hello Down There', 'Sagem', 'Comedy|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Cannery Row', 'Prestigio', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Wind Chill', 'Amoi', 'Drama|Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('National Security', 'Samsung', 'Action|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Music Man, The', 'Asus', 'Children|Comedy|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Donner Pass', 'LG', 'Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Lover''s Knot', 'alcatel', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Trailer Park of Terror', 'Plum', 'Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Meet the Parents', 'Samsung', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Trick', 'Nokia', 'Action|Crime');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Lego Movie', 'Honor', 'Action|Adventure|Animation|Children|Comedy|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Cell Count', 'Motorola', 'Horror|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Old Joy', 'Acer', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Common Threads: Stories from the Quilt', 'BLU', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Television Under the Swastika (Das Fernsehen unter dem Hakenkreuz)', 'LG', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Lisbela e o Prisioneiro (Lisbela and the Prisoner)', 'Apple', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hunter, The', 'Apple', 'Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Flaming Creatures', 'Nokia', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Paperboy, The', 'Nokia', 'Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Miguel and William (Miguel y William)', 'Lenovo', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Naked City, The', 'Samsung', 'Crime|Drama|Film-Noir|Mystery');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Key Largo', 'Samsung', 'Crime|Drama|Film-Noir|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Return of Swamp Thing, The', 'Allview', 'Comedy|Horror|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Canon', 'Intex', 'Animation');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Gojoe: Spirit War Chronicle (Gojo reisenki: Gojoe)', 'Panasonic', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('My Gun is Quick', 'Sagem', 'Mystery');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Princess Raccoon (Operetta tanuki goten)', 'Asus', 'Comedy|Fantasy|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Ice Men', 'Samsung', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Almost You', 'Pantech', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Adventures of Don Juan', 'Vodafone', 'Adventure|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('What the Day Owes the Night', 'BLU', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mean Girls', 'Samsung', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Tokyo!', 'Toshiba', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Bridge to Terabithia', 'Lenovo', 'Adventure|Children|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Black Rose Ascension (Kurobara shôten)', 'Celkon', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('New Police Story (Xin jing cha gu shi)', 'Lava', 'Action|Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Shadow of the Holy Book (Pyhän kirjan varjo)', 'Samsung', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Silent Night', 'Xiaomi', 'Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('War Is Over, The (Guerre est finie, La)', 'BQ', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Eyes Wide Shut', 'Gionee', 'Drama|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Disfigured', 'Lenovo', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('This Boy''s Life', 'Spice', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Latitudes', 'ZTE', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Blackout', 'vivo', 'Action|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Extreme Measures', 'Huawei', 'Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Get Out of My Room', 'Motorola', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Vamps', 'Samsung', 'Comedy|Horror|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Leopard Man, The', 'T-Mobile', 'Drama|Horror|Mystery|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Count of Monte Cristo', 'Huawei', 'Adventure|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Six of a Kind', 'Xiaomi', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Harold & Kumar Escape from Guantanamo Bay', 'Coolpad', 'Adventure|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Delivery Man', 'Maxwest', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Eternal Sunshine of the Spotless Mind', 'BlackBerry', 'Drama|Romance|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('A-Haunting We Will Go', 'Yezz', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Taking Off', 'Samsung', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Sexual Dependency (Dependencia sexual)', 'Meizu', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mudge Boy, The', 'ZTE', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mercury Rising', 'Meizu', 'Action|Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Man of the West', 'Samsung', 'Western');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Cranes Are Flying, The (Letyat zhuravli)', 'Ulefone', 'Drama|Romance|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Gettysburg', 'BQ', 'Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Seven Brides for Seven Brothers', 'Celkon', 'Comedy|Musical|Romance|Western');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Rocky Saga: Going the Distance, The', 'Huawei', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('War Room, The', 'Samsung', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Saving Sarah Cain', 'vivo', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Quackser Fortune Has a Cousin in the Bronx', 'BLU', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Snow Cake', 'Spice', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Carmen Jones', 'alcatel', 'Drama|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('At Middleton', 'Nokia', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Criminal Life of Archibaldo de la Cruz, The (Ensayo de un crimen)', 'Philips', 'Comedy|Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Last Man, The', 'Spice', 'Comedy|Romance|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Eminem AKA ', 'Spice', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Ondine', 'Motorola', 'Drama|Fantasy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Won Ton Ton: The Dog Who Saved Hollywood', 'QMobile', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('By the Pricking of My Thumbs (Mon petit doigt m''a dit...)', 'Huawei', 'Comedy|Mystery');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Burden of Dreams', 'Samsung', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Glory to the Filmmaker! (Kantoku · Banzai!)', 'LG', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Diana Vreeland: The Eye Has to Travel', 'Samsung', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Bilitis', 'Samsung', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('This Girl''s Life', 'verykool', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Ceremony', 'Cat', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Talhotblond:', 'Samsung', 'Documentary|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Nina Takes a Lover', 'Lenovo', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mahabharata, The', 'Gionee', 'Action|Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Thirst (Bakjwi)', 'Nokia', 'Drama|Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Bloodbrothers', 'Philips', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Champ, The', 'Samsung', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Fullmetal Alchemist the Movie: Conqueror of Shamballa (Gekijô-ban hagane no renkinjutsushi: Shanbara wo yuku mono)', 'Siemens', 'Action|Adventure|Animation|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Heart and Souls', 'Samsung', 'Comedy|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Toys', 'Prestigio', 'Comedy|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mea Maxima Culpa: Silence in the House of God', 'LG', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('War Game, The', 'Huawei', 'Documentary|Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Secret of NIMH 2: Timmy to the Rescue, The', 'Siemens', 'Adventure|Animation|Children|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Walk the Line', 'QMobile', 'Drama|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Little Engine That Could, The', 'alcatel', 'Animation|Children');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Simpsons Movie, The', 'Gionee', 'Animation|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Corridor, The (Koridorius)', 'Xiaomi', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Farsan', 'Samsung', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('God Is the Bigger Elvis', 'ZTE', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Remo Williams: The Adventure Begins', 'Motorola', 'Action|Comedy|Crime|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Liz & Dick ', 'alcatel', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Praise', 'Samsung', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Chances Are', 'Xiaomi', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Whatever It Takes', 'verykool', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Blind (Beul-la-in-deu)', 'LG', 'Drama|Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Who Is Cletis Tout?', 'Samsung', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Little Fridolf Becomes a Grandfather', 'Siemens', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('My Wife, A Body to Love', 'Nokia', '(no genres listed)');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Into the Sun', 'Samsung', 'Action|Adventure|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Brooklyn', 'Motorola', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Om Shanti Om', 'Spice', 'Action|Drama|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Slipper and the Rose, The', 'Allview', 'Adventure|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Wing and the Thigh, The (L''aile ou la cuisse)', 'Lenovo', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('She''s the Man', 'HTC', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('In Harm''s Way', 'ZTE', 'Drama|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Puppet Master 4', 'Pantech', 'Horror|Sci-Fi|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('No Time for Nuts', 'Oppo', 'Adventure|Animation|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Helter Skelter', 'Nokia', 'Crime|Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('No Logo', 'Yezz', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Camp', 'LG', 'Comedy|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('4:44 Last Day on Earth', 'Lenovo', 'Drama|Fantasy|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('America''s Sweethearts', 'Motorola', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Tuvalu', 'Motorola', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('What Goes Up', 'LG', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Chak De India!', 'Nokia', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Cutie Honey', 'Motorola', 'Action');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Mahler', 'TCL', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Lord of the Rings: The Return of the King, The', 'Celkon', 'Action|Adventure|Drama|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Johnny Dangerously', 'Vodafone', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Pearl Jam: Immagine in Cornice - Live in Italy 2006', 'Sony', 'Documentary|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('On Her Majesty''s Secret Service', 'Samsung', 'Action|Adventure|Romance|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Subject Was Roses, The', 'Sharp', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('90 Minutes (90 minutter)', 'Amoi', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Blind Faith', 'HTC', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Kangaroo Jack', 'Asus', 'Action|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Insidious', 'Acer', 'Fantasy|Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Wreck of the Mary Deare, The', 'Bird', 'Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Sid and Nancy', 'Infinix', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Silent Wedding (Nunta Muta)', 'Lenovo', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Groove', 'Siemens', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Guide to Recognizing Your Saints, A', 'Energizer', 'Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Star Wreck: In the Pirkinning', 'Nokia', 'Action|Comedy|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Ms. 45 (a.k.a. Angel of Vengeance)', 'vivo', 'Crime|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Stalker', 'Kyocera', 'Drama|Mystery|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Dumplings (Gaau ji)', 'Nokia', 'Drama|Horror|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Abyss, The', 'Asus', 'Action|Adventure|Sci-Fi|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Thanks for Sharing', 'Icemobile', 'Comedy|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Pay It Forward', 'HTC', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Blitz', 'Samsung', 'Action|Crime|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Taking Care of Business', 'Samsung', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Leonard Part 6', 'Huawei', 'Comedy|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Rocking Horse Winner, The', 'Gionee', 'Drama|Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Police Academy 5: Assignment: Miami Beach', 'Samsung', 'Comedy|Crime');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('All About My Mother (Todo sobre mi madre)', 'Vodafone', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Tales from Earthsea (Gedo Senki)', 'Telit', 'Adventure|Animation|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Love, Wedding, Marriage', 'BLU', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Princess Yang Kwei Fei (Yôkihi)', 'Unnecto', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Inn of the Sixth Happiness, The', 'Huawei', 'Adventure|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('The Orkly Kid', 'Samsung', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('In a Glass Cage (Tras el cristal)', 'Micromax', 'Drama|Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Oxygen', 'verykool', 'Drama|Musical');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Diverted', 'Motorola', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Wildest Dream, The', 'Huawei', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Saratoga Trunk', 'Samsung', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Midnight Madness', 'Micromax', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Dernier Combat, Le (Last Battle, The)', 'Sagem', 'Drama|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('All the President''s Men', 'Prestigio', 'Drama|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Incredible Melting Man, The', 'LG', 'Horror|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Striptease', 'verykool', 'Comedy|Crime');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Black Angel', 'Lenovo', 'Drama|Film-Noir|Mystery');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Xala', 'Apple', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Big Trouble', 'Yezz', 'Comedy|Crime');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Unlawful Entry', 'Samsung', 'Crime|Thriller');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('American Wedding (American Pie 3)', 'Samsung', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Michael Shayne: Private Detective', 'Apple', 'Comedy|Drama|Mystery');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Whole', 'Huawei', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Division III: Football''s Finest', 'Energizer', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Ruggles of Red Gap', 'Acer', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Junior Prom', 'Huawei', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('White Frog', 'Samsung', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Cat Came Back, The', 'Micromax', 'Action|Animation|Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('My Man Godfrey', 'Huawei', 'Comedy|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Pete Seeger: The Power of Song', 'alcatel', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Delirious', 'HTC', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('C.H.U.D.', 'Samsung', 'Horror');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Tree Grows in Brooklyn, A', 'LG', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Hansel & Gretel: Witch Hunters', 'vivo', 'Action|Fantasy|Horror|IMAX');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Bending the Rules', 'Haier', 'Action|Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Dog Problem, The', 'Motorola', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Grizzly Man', 'Motorola', 'Documentary');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('King''s Speech, The', 'Meizu', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Little Monsters', 'Motorola', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Keoma', 'Xiaomi', 'Action|Drama|Western');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Flirting With Disaster', 'Lenovo', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Keeping the Faith', 'QMobile', 'Comedy|Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Verbo', 'BLU', 'Adventure|Fantasy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Blue Swallow (Cheong yeon)', 'LG', 'Drama|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Delta Force 2 (Delta Force 2: The Colombian Connection)', 'Nokia', 'Action|Adventure|Thriller|War');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Gamera the Brave', 'Huawei', 'Action|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Gregory Go Boom', 'Nokia', 'Comedy');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Trog', 'Huawei', 'Horror|Sci-Fi');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Boy Upside Down', 'Samsung', 'Drama');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('Pardes', 'alcatel', 'Action|Comedy|Musical|Romance');
INSERT INTO JUEGO (NOMBREJUEGO, PLATAFORMA, GENERO) VALUES ('House of Small Cubes, The (Tsumiki no ie)', 'LG', 'Animation|Drama');

SELECT
*
FROM PROYECTO_PEDIDOS.JUEGO;
