-- insercion Proveedores_De_Juegos

USE PROYECTO_PEDIDOS;

INSERT INTO PROVEEDORES_DE_JUEGOS(EMPRESAPROVEEDORA, NOMBREPROVEEDOR, APELLIDOPROVEEDOR, EMAILPROVEEDOR) VALUES ( ' JuegosOnLine' , 'Franco' , 'Gomez', 'francogomez@gmail.com');
INSERT INTO PROVEEDORES_DE_JUEGOS(EMPRESAPROVEEDORA, NOMBREPROVEEDOR, APELLIDOPROVEEDOR, EMAILPROVEEDOR) VALUES ( ' JuegosPepito' , 'Marcos' , 'Oscar', 'moscar@hotmail.com');