-- GENERAR EL DDL

DROP DATABASE IF EXISTS proyecto_pedidos ; 

CREATE DATABASE proyecto_pedidos;

USE proyecto_pedidos;

-- Tabla Pedido
CREATE TABLE PEDIDO (
    IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    IDFACTURA INT,
    IDCLIENTE INT,
    IDJUEGO INT,
    IDEMPLEADO INT,
    FECHA DATETIME,
    NUMEROPEDIDO INT,
    PRODUCTO INT,
    CANTIDAD INT,
    CANCELACION DATETIME DEFAULT NULL
);

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    DNI VARCHAR(20),
    EMAIL VARCHAR(100) UNIQUE NOT NULL
);

-- Tabla EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100)
);

-- Tabla JUEGO
CREATE TABLE JUEGO (
    IDJUEGO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBREJUEGO VARCHAR(300),
    PLATAFORMA VARCHAR(50),
    GENERO VARCHAR(150)
);

-- Tabla FACTURA
CREATE TABLE FACTURA (
    IDFACTURA INT PRIMARY KEY AUTO_INCREMENT,
    IDPEDIDO INT,
    NUMEROFACTURA VARCHAR(255),
    FECHA VARCHAR(20)
);

-- FOREIGN KEYS DEFINITION

-- FACTURA

ALTER TABLE FACTURA
    ADD CONSTRAINT FK_FACTURA_PEDIDO
    FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO);

-- PEDIDO
ALTER TABLE PEDIDO
    ADD CONSTRAINT FK_PEDIDO_FACTURA
    FOREIGN KEY (IDFACTURA) REFERENCES FACTURA(IDFACTURA);

-- PEDIDO

ALTER TABLE PEDIDO
    ADD CONSTRAINT FK_PEDIDO_CLIENTE
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);
    
-- PEDIDO

ALTER TABLE PEDIDO
    ADD CONSTRAINT FK_PEDIDO_JUEGO
    FOREIGN KEY (IDJUEGO) REFERENCES JUEGO(IDJUEGO);
    
-- PEDIDO

ALTER TABLE PEDIDO
    ADD CONSTRAINT FK_PEDIDO_EMPLEADO
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);

    